on: [push]
name: Linux_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout do reposit√≥rio
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      # Login no Azure via CLI
      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login no Azure Container Registry (ACR)
      - name: 'Build and push image'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Build da imagem e push para o ACR
      - run: |
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/jokenpo:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/jokenpo:${{ github.sha }}

      # Deploy para o Azure Container Instances (ACI)
      - name: 'Deploy to Azure Container Instances'
        uses: 'azure/aci-deploy@v1'
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.RESOURCE_GROUP }}-${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/jokenpo:${{ github.sha }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: jokenpo-aci
          location: ${{ secrets.LOCATION }}
